"""Add strategy_id

Revision ID: c2947bcd2648
Revises: 69d8efdf5cf8
Create Date: 2025-06-29 14:18:51.039952

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c2947bcd2648'
down_revision: Union[str, Sequence[str], None] = '69d8efdf5cf8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('signals', sa.Column('strategy_id', sa.String(length=50), nullable=False))
    op.create_index(op.f('ix_signals_strategy_id'), 'signals', ['strategy_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_signals_strategy_id'), table_name='signals')
    op.drop_column('signals', 'strategy_id')
    # ### end Alembic commands ###
