"""Add user_id to signals table

Revision ID: c723b3f3dc1d
Revises: d28ced10b4e7
Create Date: 2025-06-30 21:01:54.636592

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c723b3f3dc1d'
down_revision: Union[str, Sequence[str], None] = 'd28ced10b4e7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('strategy_positions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('strategy_id', sa.String(length=50), nullable=False),
    sa.Column('symbol', sa.String(length=10), nullable=False),
    sa.Column('quantity', sa.Float(), nullable=False),
    sa.Column('avg_price', sa.Float(), nullable=True),
    sa.Column('total_invested', sa.Float(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('strategy_id', 'symbol', name='uq_strategy_symbol')
    )
    op.create_index(op.f('ix_strategy_positions_id'), 'strategy_positions', ['id'], unique=False)
    op.create_index(op.f('ix_strategy_positions_strategy_id'), 'strategy_positions', ['strategy_id'], unique=False)
    op.create_index(op.f('ix_strategy_positions_symbol'), 'strategy_positions', ['symbol'], unique=False)
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('username', sa.String(length=100), nullable=False),
    sa.Column('password_hash', sa.String(length=255), nullable=False),
    sa.Column('full_name', sa.String(length=255), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('is_verified', sa.Boolean(), nullable=True),
    sa.Column('is_admin', sa.Boolean(), nullable=True),
    sa.Column('verification_token', sa.String(length=255), nullable=True),
    sa.Column('reset_token', sa.String(length=255), nullable=True),
    sa.Column('reset_token_expires', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.Column('last_login', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_index(op.f('ix_users_id'), 'users', ['id'], unique=False)
    op.create_index(op.f('ix_users_username'), 'users', ['username'], unique=True)
    op.add_column('signals', sa.Column('user_id', sa.Integer(), nullable=True))
    op.create_index(op.f('ix_signals_user_id'), 'signals', ['user_id'], unique=False)
    op.create_foreign_key(None, 'signals', 'users', ['user_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'signals', type_='foreignkey')
    op.drop_index(op.f('ix_signals_user_id'), table_name='signals')
    op.drop_column('signals', 'user_id')
    op.drop_index(op.f('ix_users_username'), table_name='users')
    op.drop_index(op.f('ix_users_id'), table_name='users')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    op.drop_index(op.f('ix_strategy_positions_symbol'), table_name='strategy_positions')
    op.drop_index(op.f('ix_strategy_positions_strategy_id'), table_name='strategy_positions')
    op.drop_index(op.f('ix_strategy_positions_id'), table_name='strategy_positions')
    op.drop_table('strategy_positions')
    # ### end Alembic commands ###
